[package]
name = "osu_favorites_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "^0.11.17", features = ["blocking"] }
dotenv = "^0.15"
serde_json = "^1.0.96"
